### PR TITLE
Add GPUArrays.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
@SimonDanisch Have you seen these errors before? Check the `Initializing container` for package build output.

**Comment by SimonDanisch** [comment]
Oh what? I hate that error and thought I got rid of it... Maybe not in the tagged version. Let me have a look!

**Comment by SimonDanisch** [comment]
Aha, Matcha might be the culprit... But I'd really like to know why the precompilation error is not deterministic...

**Comment by SimonDanisch** [comment]
Okay, Matcha is tagged. What needs to be done now? And what if I want to checkout master branches?

**Comment by maleadt** [comment]
> What needs to be done now?

Nothing, I restarted the build.

> And what if I want to checkout master branches?

Not supported right now. Shouldn't be a requirement; users ought to be able to install packages the regular way.

**Comment by SimonDanisch** [comment]
Okay! I guess this needs clfft and clblas :) I will try and tag GPUArrays today!

**Comment by maleadt** [comment]
Yay, passes tests!

**Pull request merged**
