### PR TITLE
Add Knet.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
@denizyuret How do I check if Knet uses GPU arrays successfully? Does this output look OK?
If so, I guess this image could be useful for you to advertise to potential users.

**Comment by denizyuret** [comment]
@maleadt You can check for it using the Knet.gpu() function, which returns a device id.  If the result is >=0 then we have successfully initialized a gpu.  Which output are you referring to?  @ozanarkancan can you test this docker image?

**Comment by maleadt** [comment]
The package build and test output from: http://ci.maleadt.net:8010/#/builders/41/builds/91

**Comment by ozanarkancan** [comment]
I have tested the image and Knet passes all tests.

**Comment by maleadt** [comment]
OK, and I also verified the output of `gpu()` with the image from this branch (that comes with Knet pre-installed):

```
julia> using Knet

julia> Knet.gpu()
0
```

**Pull request merged**
